version: '3'

services:
  web:
    build: .
    command: sh -c "hypercorn Application:Application --port=8080 --host=0.0.0.0"
    env_file:
      - .env.production
    ports:
      - 8080:8080
    volumes:
      - .:/888BotRestructure